# Module 2: Colab Assignment

## Become familiar using a Colab notebook

**Problem 1: (20 pts)**

Import `numpy` as `np` and `pandas` as `pd`


In [4]:
import numpy as np
import pandas as pd


**Problem 2: (40 pts)**

Create a simple DataFrame as follows:


1. Create a 5x3 NumPy array
2. Create a Python list that contains the column names (three columns in total)
3. Create a DataFrame
4. Print the DataFrame


In [5]:
#Step 1

fivethree = np.eye(5,3)


In [6]:
#Step 2

lst = ['one','two','three']

In [7]:
#Step 3
df = pd.DataFrame(data=fivethree, columns=lst)

In [8]:
#Step 4
print(fivethree)
print(list)
print(df)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'list'>
   one  two  three
0  1.0  0.0    0.0
1  0.0  1.0    0.0
2  0.0  0.0    1.0
3  0.0  0.0    0.0
4  0.0  0.0    0.0


**Problem 3: (20 pts)**

1. Write a function to convert seconds into minutes (output should be an integer number).
2. Provide an example using this function and show on the screen the `input` and `output`. For example:

`Input: Seconds = 125 `

`Output: Minutes = 2`


In [9]:
#Step 1
def secmin (seconds):
  minutes = seconds / 60
  return minutes

In [10]:
#Step 2
input = 120
print (input)

output=secmin(input)
print (output)


120
2.0


**Problem 4: (20 pts)**

Load the CSV data file as follows:

1. Find the data file on Canvas. 

   Go to `Files` -> `Data Files` -> `SOCR-HeightWeight.csv`

2. Upload the CSV file in Colab 
3. Load the CSV file into a DataFrame named `df`
3. Print the DataFrame `df`

In [11]:
#Step 3: To run this you need to do step 1 & 2 first.

df = pd.read_csv('/content/SOCR-HeightWeight.csv')

In [12]:
#Step 4

print(df)

       Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]
